### ISSUE TITLE
Unwanted gist "markers" on page

### ISSUE THREAD

**Issue by JESii** [jsbin/learn#101]
Love jsBin - thanks for this!
When I work in the javascript editor, I get lots of those gist hot spots 
![image](https://user-images.githubusercontent.com/486/29344270-69846e48-81eb-11e7-9bf3-82bd39a8d4e8.png) scattered along the right edge of the screen. They get in the way and obscure portions of the code.
How do I just turn off that feature entirely?

**Comment by remy** [comment]
You're using a browser plugin that's causing these. To confirm either try another browser, or privacy mode
