### ISSUE TITLE
Special string characters dont work in jsbin

### ISSUE THREAD

**Issue by HexScript** [jsbin/learn#112]
if i use code

 console.log("Fine \\"dude\\" here");

expected result should be according to ECMAScript javascript spesification:

"Fine "dude" here"

But js bin show result like this:

"Fine \\"dude\\" here"

https://www.w3schools.com/js/tryit.asp?filename=tryjs_string_escape_quotes2

**Comment by remy** [comment]
That's just the way the bespoke console is printing. It's been fixed in v5's console, which you can preview here: https://jsconsole.com/?console.log%28%22Fine%20%5C%22dude%5C%22%20here%22%29
