### ISSUE TITLE
Q. How to populate bin?

### ISSUE THREAD

**Issue by bsvensson** [jsbin/learn#55]
On https://jsbin.com/help/populating-bins and https://github.com/jsbin/learn/blob/master/public/help/populating-bins.md it says `This article will walk through how` ... and then it ends abruptly.  I'm not sure if there is supposed to be a link to something that already exist, or if it is waiting for someone to create that content...

**Comment by cristiscu** [comment]
I'm also very interested in this issue, any progress on it?

It seems we could only issue a POST for it, and this is a paid option. Please reconsider. Similar products such as jsFiddle and CodePen offer this feature for free.

**Comment by bsvensson** [comment]
(I'd forgotten about this old issue).

Actually, this has been working for quite a while, up until a few weeks ago when jsbin.com got updated.  There's a new issue for re-instating it at https://github.com/jsbin/jsbin/issues/3059

**Comment by bsvensson** [comment]
To answer the original question - see sample at https://jsbin.com/dimulul/edit?html,js,output
