### ISSUE TITLE
dropbox integration not working

### ISSUE THREAD

**Issue by sfbwalder** [jsbin/learn#57]
I linked my pro jsbin account to my drop box account.  The app/jsbin directory is created in drop box.  I create a new bin, and make changes.  Nothing shows up in the Apps/jsbin folder in drop box as the the demo shows it should.

Did I miss some configuration somewhere?  It's not backing up to drop box by magic as the help demo shows.  I don't see any errors in the browser console, and the browser network trace shows all the save requests as successful.

I am logged in jsbin with this github account.  The dropbox account is a different id and email than this github / jsbin account.

Did I mess something up?  Are there error message somewhere else I can look?

Please help, Thanks, Ben
.

**Comment by remy** [comment]
I've restarted the process that does the dropbox sync - can you check again
to see if it's working again for you?

Cheers for the report too!

**Comment by sfbwalder** [comment]
It's working!  Thanks.

Sorry for the delayed response due to time away.
