### ISSUE TITLE
Where is preview

### ISSUE THREAD

**Issue by GigglingDolphins** [jsbin/learn#58]
On all the tutorials that I have watched the user just enters some javascript and then select preview to run it. I do not see a preview button, Am I missing something here?

**Comment by jmitz** [comment]
I believe the output is immediately updated as you modify the JavaScript, unless you have "Auto-run JS" unchecked. If "Auto-run JS" is unchecked you will need to click the "Run with JS" button to start the JavaScript.

**Comment by GigglingDolphins** [comment]
I have tried and tried but when a tool that is suppose to help you becomes a roadblock its time to put it into the trash bucket. jsbin is just that tool, I have searched, I have asked, and I have searched some more but I cannot get this tool to work. I enter some very simple VALID javascript but there is no way to run it. If someone can explain it (I have found some videos that show a code and preview button but they are not in the latest version and their help well lets just say it sucks) that would be great....until then this is just useless to me

**Comment by remy** [comment]
That's fine if the tool is useless to you. I'm not looking to grow the free userbase. I suspect there's either something not working on jsbin on your machine or you just don't get it, either way, there are other tools you can use. Good luck.

**Comment by GigglingDolphins** [comment]
What a concept, a potential customer submits a problem and you blow them off. So here is what we did:
1: I had 5 other developers try the same problem on different machines...guess what, they have the same problem
2: We really thought that we might buy you tool, but it your customer support is to act like it is my problem and not yours...well good luck to you.
3: We will make sure to post this on every development board that we can....hey we just want to help you get customers that relish the concept of getting blown off by customer support.
 
Good luck in your venture, all you need now is a wagon and some snake oil and you will be all set.
 
--------- Original Message --------- Subject: Re: [learn] Where is preview (#58)

**Comment by remy** [comment]
(3) seems like a lot of effort, but if you have the time, go for it.

Thanks again.

**Comment by GigglingDolphins** [comment]
Hello! 

Have  you  already seen  that coolest  stuff  ever? What do  you think abou it? Check it out <http://hiphothange.dvo2000.com/e4ztemqs>


Best, jack
