### ISSUE TITLE
save a project

### ISSUE THREAD

**Issue by Beethoven5516** [jsbin/learn#76]
How should I save a project? 
How will It work if I want somebody see only one of my projects?

**Comment by remy** [comment]
If you type, your project is saved.

**Comment by Beethoven5516** [comment]
If I type the project will be saved. I do not understand the sentence. What should I type the project to be saved. Are you refereeing as I type the project  will be saved without any name? If it is the case how do I find the project again or write new project? I did not know how to save my project so I copy the project on notepad and save it in my computer directory.

**Comment by remy** [comment]
As soon as you type into the textbox (HTML, CSS, JS) jsbin will save and
create a new URL for you.

The URL updates in the URL bar.

If you create a free account, you can use the file:open menu to retrieve
older bins you've made.
