### ISSUE TITLE
change credit card info

### ISSUE THREAD

**Issue by Winger89MZ** [jsbin/learn#80]
(apologies if this is a repeat: it didn't seem to go through)

I've got the Pro Monthly subscription, due to expire July 10.  Unfortunately, the credit card I used is no longer valid.  I'm trying to figure out how to change my credit card info... will it be necessary to cancel my subscription and then re-upgrade to pro?  I don't want to lose anything...

Thanks!

**Comment by remy** [comment]
Hey, this is a fairly old issue, but if you got to https://jsbin.com/account/subscription you can change your card details (I added the feature a short while ago).
