### ISSUE TITLE
Still confused on getting my JS functions to run

### ISSUE THREAD

**Issue by RSmithBothell** [jsbin/learn#86]
Please see https://jsbin.com/hazifu/edit?html,js,console,output

I still have the 'wrong' paths for your site in the javascript references.  Remove them COMPLETELY???

When I `$(document).ready(functionname) ;`
how can I get jsbin to run the function that I put into the JS window?

THANKS!

**Comment by remy** [comment]
All of these are relative paths to some (random?) scripts.

You'll have to host these scripts somewhere for jsbin to see them: https://jsbin.com/hazifu/edit?html,output#H:L7-14

JS Bin pro offers asset hosting, but you can equally host them anywhere on the public web. An absolute URL can be seen on line 16 for example.
