### ISSUE TITLE
How do I delete bins?

### ISSUE THREAD

**Issue by j-go-j** [jsbin/learn#95]
Hi--I'm new to js bin.  how do I delete bins?

**Comment by remy** [comment]
File menu, delete.

**Comment by j-go-j** [comment]
Thanks for your answer.

FYI, at first, when I clicked FILE/MY BINS and highlighted the one I wanted
to delete and then hit CMD-SHIFT-DELETE, I sometimes (not always) got a
message that said "You don't own this bin"--so I couldn't delete that way.

But, when I actually opened the bin and hit CMD-SHIFT-DEL, that worked.
________________________________________________________
Also--I'm supe-new so please forgive my ignorance and thanks for your
patience. When I hit "run with JS" in my JS Bin, nothing happens.  It's
probably because my code is bad.  But, if you could take a look at the
message I got below when I installed JS Bin I'd appreciate it--and let me
know if this is a problem.  I installed Node v6.10.3 and npm v.3.10.10.

When I tried to install JS Bin, I got the below.  (RTF file of the same
attached).

[image: Inline image 1]
After getting this message, I ran the below commands anyway:

   - npm install -g grunt-cli
   - npm install --dev
   - grunt build

And I got this:

[image: Inline image 3]

So, when I write some JS and hit "run" in JS Bin, I see no ouput.

thanks,




*Jocelyn*
