### ISSUE TITLE
How big is too big for saving?

### ISSUE THREAD

**Issue by elliotland** [jsbin/learn#96]
When I try to create a Bin and get the tip that "Sorry this bin is too large for us to save," what is the max size I can use in a bin?

Edit: Sorry if this is a duplicate. I searched before but did not find anything.

**Comment by remy** [comment]
Let's say 64K. That seems big enough. I'm pretty sure that's right based on the config

**Comment by markho90** [comment]
Hi Remy,

73Kb size can be save but 74Kb size can not be size. How ??
